#ifndef _JoyTerrainMaterialDebugSwitch_H_
#define _JoyTerrainMaterialDebugSwitch_H_

#ifndef g_BottomLayerEnable
#define g_BottomLayerEnable 1
#endif

#ifndef g_MiddleLayerEnable
#define g_MiddleLayerEnable 0
#endif

#ifndef g_UpperLayerEnable
#define g_UpperLayerEnable 0
#endif

#ifndef g_DetailLayerEnable
#define g_DetailLayerEnable 0
#endif

#ifndef g_NormalLayerEnable
#define g_NormalLayerEnable 0
#endif

#ifndef g_LightMapEnable
#define g_LightMapEnable 0
#endif

#ifndef g_ColorMapEnable
#define g_ColorMapEnable 0
#endif

#ifndef g_BlendLayerEnable
#define g_BlendLayerEnable 0
#endif

#ifndef g_NoLighting
#define g_NoLighting 	0
#endif

#ifndef SL1
#define SL1 s0
#endif

#ifndef SL2
#define SL2 s1
#endif

#ifndef SL3
#define SL3 s2
#endif

#ifndef SLDetail
#define SLDetail s3
#endif

#ifndef SLNormal
#define SLNormal s4
#endif

#ifndef SLBlend
#define SLBlend s5
#endif

#ifndef SC
#define SC s6
#endif

#ifndef SCC
#define SCC						s7
#endif

#endif